[package]
name = "twink"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
authors = ["Clover Johnson <clover.johnson@mailfence.com>"]

[dependencies]
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_12"] }
